### ISSUE TITLE
Wrong direction

### ISSUE THREAD

**Issue by afshiney** [amidesfahani/nova-persian-date#1]
Hey there,
Recently I spotted an issue on **time picker** when using RTL package for persian styled panels,

<hr>

![Screen Shot 2021-06-28 at 12 01 09 PM](https://user-images.githubusercontent.com/24396223/123597453-9a992d80-d808-11eb-812f-12e311c761ec.png)

<hr>

For example the screenshot above is pointing to 07:54.

**Comment by mostafaznv** [comment]
Hi @afshiney 

Just add the following css to your nova panel:
```
.vpd-time .vpd-time-h .vpd-counter, .vpd-time .vpd-time-m .vpd-counter {
    direction: ltr !important;
}
```
